//  common

export const StorageKey_OpenAppOfDayCount = 'StorageKey_OpenAppOfDayCount'
export const StorageKey_OpenAppOfDayCountForDate = 'StorageKey_OpenAppOfDayCountForDate'

export const StorageKey_CachedIAP = 'StorageKey_CachedIAP'
export const StorageKey_LastCheckFirstOpenOfTheDay = 'StorageKey_LastCheckFirstOpenOfTheDay'
export const StorageKey_FirstTimeInstallTick = 'StorageKey_FirstTimeInstallTick'
export const StorageKey_TrackedNewlyInstall = 'StorageKey_TrackedNewlyInstall'
export const StorageKey_OpenAppTotalCount = 'StorageKey_OpenAppTotalCount'
export const StorageKey_LastAskForUpdateApp = 'StorageKey_LastAskForUpdateApp'
export const StorageKey_PressUpdateObject = 'StorageKey_PressUpdateObject'
export const StorageKey_LastInstalledVersion = 'StorageKey_LastInstalledVersion'
export const StorageKey_NeedToShowWhatsNewFromVer = 'StorageKey_NeedToShowWhatsNewFromVer'
export const StorageKey_LastFreshlyOpenApp = 'StorageKey_LastFreshlyOpenApp'
export const StorageKey_Streak = 'StorageKey_Streak'
export const StorageKey_OpenAt = 'StorageKey_OpenAt'
export const StorageKey_SubscribeData = 'StorageKey_SubscribeData'
export const StorageKey_OneQuyAppLastSubDownload = 'StorageKey_OneQuyAppLastSubDownload'
export const StorageKey_CacheEventNotification = 'StorageKey_CacheEventNotification'
export const StorageKey_ForceDev = 'StorageKey_ForceDev'
export const StorageKey_UserID = 'StorageKey_UserID'
export const StorageKey_LoopSetValueFirebase = 'StorageKey_LoopSetValueFirebase'
export const StorageKey_DidFetchUserDataOnNewlyInstall = 'StorageKey_DidFetchUserDataOnNewlyInstall'
export const StorageKey_ShowedWelcomeScreen = 'StorageKey_ShowedWelcomeScreen'
export const StorageKey_RevenueCatPackages = 'StorageKey_RevenueCatPackages'
export const StorageKey_CurrentAllNotifications = 'StorageKey_CurrentAllNotifications'
export const StorageKey_LastPushTick = 'StorageKey_LastPushTick'
export const StorageKey_StartUsingAppTick = 'StorageKey_StartUsingAppTick'

// specific